# Generated by Django 3.1.4 on 2021-01-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='tel',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=11),
        ),
    ]
