# Generated by Django 3.1.4 on 2021-01-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_auto_20210101_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pwd',
            field=models.CharField(default=123, max_length=20),
        ),
    ]
