# Generated by Django 3.1.4 on 2021-01-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_user_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pwd',
            field=models.CharField(max_length=20),
        ),
    ]
