# Generated by Django 3.1.4 on 2021-01-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_auto_20210103_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
    ]
