# Generated by Django 3.1.4 on 2021-01-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_auto_20210103_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='isavailable',
            field=models.BooleanField(default=True),
        ),
    ]
